deploy: 
    stage: deploy 
    image: dotsunited/git-ftp 
    only: 
      - master 
 
    script: 
      - git-ftp push -v --auto-init --insecure --user $FTP_USERNAME --passwd $FTP_PASSWORD "$FTP_HOST" 